
name: Build docker images
on:
  push:
      branches:
        - master
      paths:
        - 'crow/**'
     
jobs:
  build-crow-dockerrmi:
    name: Build docker stack for CROW
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update && docker --version
      - name: Build backend image
        run: |
          sudo bash build_docker_crow.sh

      - name: Push images CROW
        run: |
          docker login -u="$user" -p="$pass" && docker push slumps/crow2:latest
        env:
          user: ${{secrets.DOCKER_USER}}
          pass: ${{secrets.DOCKER_PASS}}

      - name: Push images CROW standalone
        run: |
          docker login -u="$user" -p="$pass" && docker push slumps/crow2:standalone
        env:
          user: ${{secrets.DOCKER_USER}}
          pass: ${{secrets.DOCKER_PASS}}
